"""Configuration and constants for the demo2 execution system."""

import os
from typing import Tuple

TRUE_VALUES = {"1", "true", "yes", "on"}
FALSE_VALUES = {"0", "false", "no", "off"}


def env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return parse_env_bool(name, value)


def parse_env_bool(name: str, value: str) -> bool:
    normalized = value.strip().lower()
    if normalized in TRUE_VALUES:
        return True
    if normalized in FALSE_VALUES:
        return False
    raise RuntimeError(
        f"{name} must be one of: "
        f"{', '.join(sorted(TRUE_VALUES | FALSE_VALUES))}."
    )


CLOUD_RENDERING = env_bool("CloudRendering", True)
RENDER_IMAGE = env_bool("renderImage", False) # True
NAVIGATION_GRID_SIZE = 0.25
AGENT_CLEARANCE_DISTANCE = 0.35
OBJECT_FOOTPRINT_CLEARANCE = 0.05
OPEN_OBJECT_FOOTPRINT_CLEARANCE = 0.2
TELEPORT_CANDIDATE_LIMIT = 10
NAVIGATION_CHUNK_STEPS = 4
INTERACTION_MAX_PASS_STEPS = 30
TOP_VIEW_NAME = "top_view"
DIRECTIONAL_VIEW_NAMES = ("front_view", "back_view", "left_view", "right_view")
THIRD_PARTY_VIEW_NAMES = (TOP_VIEW_NAME,) + DIRECTIONAL_VIEW_NAMES
CAMERA_HEIGHT_OFFSET = 1.8
TOP_VIEW_HEIGHT_OFFSET = -0.3
TOP_VIEW_CAMERA_FOV = 90
DIRECTIONAL_CAMERA_EDGE_INSET = 1.0
DIRECTIONAL_CAMERA_PITCH = 0.0
DIRECTIONAL_CAMERA_FOV = 70
LOCAL_TOP_VIEW_MIN_HEIGHT = 4.0
LOCAL_TOP_VIEW_EXTENT_SCALE = 0.9
AabbBounds = Tuple[float, float, float, float, float, float]
SceneObjectFootprint = Tuple[str, AabbBounds, float]
PLACEMENT_RESTRICTIONS = {
    "AlarmClock": (
        "Box",
        "Dresser",
        "Desk",
        "SideTable",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "CounterTop",
        "Shelf",
        "Chair",
        "Stool",
    ),
    "Apple": (
        "Pot",
        "Pan",
        "Bowl",
        "Microwave",
        "Fridge",
        "Plate",
        "Sink",
        "SinkBasin",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "Desk",
        "CounterTop",
        "GarbageCan",
        "Dresser",
    ),
    "AppleSliced": (
        "Pot",
        "Pan",
        "Bowl",
        "Microwave",
        "Fridge",
        "Plate",
        "Sink",
        "SinkBasin",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "Desk",
        "CounterTop",
        "GarbageCan",
        "Dresser",
    ),
    "BaseballBat": (
        "Bed",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "Desk",
        "CounterTop",
        "Floor",
    ),
    "BasketBall": (
        "Sofa",
        "ArmChair",
        "Dresser",
        "Desk",
        "Bed",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Stool",
        "Chair",
        "Floor",
    ),
    "Book": (
        "Sofa",
        "ArmChair",
        "Box",
        "Ottoman",
        "Dresser",
        "Desk",
        "Bed",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "Stool",
        "Chair",
        "Floor",
    ),
    "Boots": ("Floor",),
    "Bottle": (
        "Fridge",
        "Box",
        "Dresser",
        "Desk",
        "Sink",
        "SinkBasin",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "GarbageCan",
    ),
    "Bowl": (
        "Microwave",
        "Fridge",
        "Dresser",
        "Desk",
        "Sink",
        "SinkBasin",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
    ),
    "Box": (
        "Sofa",
        "ArmChair",
        "Dresser",
        "Desk",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Ottoman",
        "Stool",
        "Chair",
        "Floor",
    ),
    "Bread": (
        "Microwave",
        "Fridge",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "Desk",
        "CounterTop",
        "GarbageCan",
        "Plate",
    ),
    "BreadSliced": (
        "Microwave",
        "Fridge",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "Desk",
        "CounterTop",
        "GarbageCan",
        "Toaster",
        "Plate",
    ),
    "ButterKnife": (
        "Pot",
        "Pan",
        "Bowl",
        "Mug",
        "Plate",
        "Cup",
        "Sink",
        "SinkBasin",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "Desk",
        "CounterTop",
        "Drawer",
    ),
    "Candle": (
        "Box",
        "Dresser",
        "Desk",
        "Toilet",
        "Cart",
        "Bathtub",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "Stool",
        "Chair",
    ),
    "CD": (
        "Box",
        "Ottoman",
        "Dresser",
        "Desk",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "GarbageCan",
        "Safe",
        "Sofa",
        "ArmChair",
        "Stool",
        "Chair",
        "Footstool",
    ),
    "CellPhone": (
        "Sofa",
        "ArmChair",
        "Box",
        "Ottoman",
        "Dresser",
        "Desk",
        "Bed",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "Safe",
        "Stool",
        "Chair",
        "Footstool",
    ),
    "Cloth": (
        "Sofa",
        "ArmChair",
        "Box",
        "Ottoman",
        "Dresser",
        "LaundryHamper",
        "Desk",
        "Toilet",
        "Cart",
        "BathtubBasin",
        "Bathtub",
        "Sink",
        "SinkBasin",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "GarbageCan",
        "Stool",
        "Chair",
        "Footstool",
        "Floor",
    ),
    "CreditCard": (
        "Sofa",
        "ArmChair",
        "Box",
        "Ottoman",
        "Dresser",
        "Desk",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "Stool",
        "Chair",
        "Footstool",
    ),
    "Cup": (
        "Microwave",
        "Fridge",
        "Dresser",
        "Desk",
        "Sink",
        "SinkBasin",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
    ),
    "DishSponge": (
        "Pot",
        "Pan",
        "Bowl",
        "Plate",
        "Box",
        "Toilet",
        "Cart",
        "BathtubBasin",
        "Bathtub",
        "Sink",
        "SinkBasin",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "GarbageCan",
    ),
    "Egg": (
        "Pot",
        "Pan",
        "Bowl",
        "Microwave",
        "Fridge",
        "Plate",
        "Sink",
        "SinkBasin",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "GarbageCan",
    ),
    "EggCracked": (
        "Pot",
        "Pan",
        "Bowl",
        "Microwave",
        "Fridge",
        "Plate",
        "Sink",
        "SinkBasin",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "GarbageCan",
    ),
    "Fork": (
        "Pot",
        "Pan",
        "Bowl",
        "Mug",
        "Plate",
        "Cup",
        "Sink",
        "SinkBasin",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Drawer",
    ),
    "HandTowel": ("HandTowelHolder",),
    "Kettle": (
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Sink",
        "SinkBasin",
        "Cabinet",
        "StoveBurner",
        "Shelf",
    ),
    "KeyChain": (
        "Sofa",
        "ArmChair",
        "Box",
        "Ottoman",
        "Dresser",
        "Desk",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "Safe",
        "Stool",
        "Chair",
    ),
    "Knife": (
        "Pot",
        "Pan",
        "Bowl",
        "Mug",
        "Plate",
        "Sink",
        "SinkBasin",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Drawer",
    ),
    "Ladle": (
        "Pot",
        "Pan",
        "Bowl",
        "Plate",
        "Sink",
        "SinkBasin",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Drawer",
    ),
    "Laptop": (
        "Sofa",
        "ArmChair",
        "Ottoman",
        "Dresser",
        "Desk",
        "Bed",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Stool",
        "Chair",
        "Footstool",
    ),
    "Lettuce": (
        "Pot",
        "Pan",
        "Bowl",
        "Fridge",
        "Plate",
        "Sink",
        "SinkBasin",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "GarbageCan",
    ),
    "LettuceSliced": (
        "Pot",
        "Pan",
        "Bowl",
        "Fridge",
        "Plate",
        "Sink",
        "SinkBasin",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "GarbageCan",
    ),
    "Mug": (
        "CoffeeMachine",
        "Microwave",
        "Fridge",
        "Plate",
        "Box",
        "Dresser",
        "Desk",
        "Cart",
        "Sink",
        "SinkBasin",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
    ),
    "Newspaper": (
        "Sofa",
        "ArmChair",
        "Ottoman",
        "Dresser",
        "Desk",
        "Bed",
        "Toilet",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "GarbageCan",
        "Stool",
        "Chair",
        "Footstool",
        "Floor",
    ),
    "Pan": (
        "DiningTable",
        "CounterTop",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "Sink",
        "SinkBasin",
        "Cabinet",
        "StoveBurner",
        "Fridge",
    ),
    "PaperTowelRoll": (
        "Box",
        "Toilet",
        "Cart",
        "Bathtub",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "GarbageCan",
    ),
    "Pen": (
        "Mug",
        "Box",
        "Dresser",
        "Desk",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "GarbageCan",
        "Stool",
        "Chair",
        "Footstool",
    ),
    "Pencil": (
        "Mug",
        "Box",
        "Dresser",
        "Desk",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "GarbageCan",
        "Stool",
        "Chair",
        "Footstool",
    ),
    "PepperShaker": (
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Drawer",
        "Cabinet",
        "Shelf",
    ),
    "Pillow": ("Sofa", "ArmChair", "Ottoman", "Bed", "Stool", "Chair"),
    "Plate": (
        "Microwave",
        "Fridge",
        "Dresser",
        "Desk",
        "Sink",
        "SinkBasin",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
    ),
    "Plunger": ("Cart", "Cabinet", "Floor"),
    "Pot": (
        "StoveBurner",
        "Fridge",
        "Sink",
        "SinkBasin",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
    ),
    "Potato": (
        "Pot",
        "Pan",
        "Bowl",
        "Microwave",
        "Fridge",
        "Plate",
        "Sink",
        "SinkBasin",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "GarbageCan",
    ),
    "PotatoSliced": (
        "Pot",
        "Pan",
        "Bowl",
        "Microwave",
        "Fridge",
        "Plate",
        "Sink",
        "SinkBasin",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "GarbageCan",
    ),
    "RemoteControl": (
        "Sofa",
        "ArmChair",
        "Box",
        "Ottoman",
        "Dresser",
        "Desk",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "Stool",
        "Chair",
        "Footstool",
    ),
    "SaltShaker": (
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Drawer",
        "Cabinet",
        "Shelf",
    ),
    "SoapBar": (
        "Toilet",
        "Cart",
        "Bathtub",
        "BathtubBasin",
        "Sink",
        "SinkBasin",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "GarbageCan",
    ),
    "SoapBottle": (
        "Dresser",
        "Desk",
        "Toilet",
        "Cart",
        "Bathtub",
        "Sink",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "GarbageCan",
    ),
    "Spatula": (
        "Pot",
        "Pan",
        "Bowl",
        "Plate",
        "Sink",
        "SinkBasin",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Drawer",
    ),
    "Spoon": (
        "Pot",
        "Pan",
        "Bowl",
        "Mug",
        "Plate",
        "Cup",
        "Sink",
        "SinkBasin",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Drawer",
    ),
    "SprayBottle": (
        "Dresser",
        "Desk",
        "Toilet",
        "Cart",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "GarbageCan",
    ),
    "Statue": (
        "Box",
        "Dresser",
        "Desk",
        "Cart",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Safe",
    ),
    "TeddyBear": (
        "Bed",
        "Sofa",
        "ArmChair",
        "Ottoman",
        "Dresser",
        "Desk",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Safe",
        "Stool",
        "Chair",
    ),
    "TennisRacket": (
        "Dresser",
        "Desk",
        "Bed",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Stool",
        "Chair",
        "Floor",
    ),
    "TissueBox": (
        "Box",
        "Dresser",
        "Desk",
        "Toilet",
        "Cart",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "GarbageCan",
        "Stool",
        "Chair",
        "Footstool",
    ),
    "ToiletPaper": (
        "Dresser",
        "Desk",
        "Toilet",
        "ToiletPaperHanger",
        "Cart",
        "Bathtub",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "GarbageCan",
        "Stool",
        "Chair",
    ),
    "ToiletPaperRoll": (
        "Dresser",
        "Desk",
        "Toilet",
        "ToiletPaperHanger",
        "Cart",
        "Bathtub",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "GarbageCan",
        "Stool",
    ),
    "Tomato": (
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Sink",
        "SinkBasin",
        "Pot",
        "Bowl",
        "Fridge",
        "GarbageCan",
        "Plate",
    ),
    "TomatoSliced": (
        "DiningTable",
        "CounterTop",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "Sink",
        "SinkBasin",
        "Pot",
        "Bowl",
        "Fridge",
        "GarbageCan",
        "Plate",
    ),
    "Towel": ("TowelHolder",),
    "Vase": (
        "Box",
        "Dresser",
        "Desk",
        "Cart",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Safe",
    ),
    "Watch": (
        "Box",
        "Dresser",
        "Desk",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "Safe",
        "Stool",
        "Chair",
        "Footstool",
    ),
    "WateringCan": (
        "Dresser",
        "Desk",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Drawer",
        "Stool",
        "Chair",
        "Floor",
    ),
    "WineBottle": (
        "Fridge",
        "Dresser",
        "Desk",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "GarbageCan",
    ),
    "Dumbbell": (
        "Dresser",
        "Desk",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Bed",
        "Chair",
        "ArmChair",
        "Sofa",
        "Stool",
        "Footstool",
        "Floor",
    ),
    "AluminumFoil": (
        "Dresser",
        "Drawer",
        "Desk",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
    ),
    "TableTopDecor": (
        "Dresser",
        "Desk",
        "Cabinet",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
    ),
    "TargetCircle": (
        "Dresser",
        "Desk",
        "DiningTable",
        "TVStand",
        "CoffeeTable",
        "SideTable",
        "CounterTop",
        "Shelf",
        "Floor",
    ),
}
